import React from 'react';
import { 
  LayoutDashboard, 
  BookOpen, 
  BrainCircuit,
  Code2,
  Zap,
  Users,
  Wand2,
  Trophy,
  Shield,
  Database,
  Cloud,
  Cpu,
  Globe,
  Terminal,
  Layers,
  Settings,
  Lock,
  Server,
  HardDrive,
  Wifi,
  FileText,
  Mail,
  MessageSquare,
  Bell,
  Calendar,
  Clock,
  Target,
  Flag,
  Briefcase,
  GraduationCap,
  Building,
  Home,
  Heart,
  Star,
  Flame,
  Sun,
  Moon,
  Coffee,
  Activity
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ReactNode> = {
  'Code2': <Code2 className="w-6 h-6" />,
  'BrainCircuit': <BrainCircuit className="w-6 h-6" />,
  'Zap': <Zap className="w-6 h-6" />,
  'Users': <Users className="w-6 h-6" />,
  'Wand2': <Wand2 className="w-6 h-6" />,
  'LayoutDashboard': <LayoutDashboard className="w-6 h-6" />,
  'Activity': <Activity className="w-6 h-6" />,
  'Trophy': <Trophy className="w-6 h-6" />,
  'BookOpen': <BookOpen className="w-6 h-6" />,
  'Shield': <Shield className="w-6 h-6" />,
  'Database': <Database className="w-6 h-6" />,
  'Cloud': <Cloud className="w-6 h-6" />,
  'Cpu': <Cpu className="w-6 h-6" />,
  'Globe': <Globe className="w-6 h-6" />,
  'Terminal': <Terminal className="w-6 h-6" />,
  'Layers': <Layers className="w-6 h-6" />,
  'Settings': <Settings className="w-6 h-6" />,
  'Lock': <Lock className="w-6 h-6" />,
  'Server': <Server className="w-6 h-6" />,
  'HardDrive': <HardDrive className="w-6 h-6" />,
  'Wifi': <Wifi className="w-6 h-6" />,
  'FileText': <FileText className="w-6 h-6" />,
  'Mail': <Mail className="w-6 h-6" />,
  'MessageSquare': <MessageSquare className="w-6 h-6" />,
  'Bell': <Bell className="w-6 h-6" />,
  'Calendar': <Calendar className="w-6 h-6" />,
  'Clock': <Clock className="w-6 h-6" />,
  'Target': <Target className="w-6 h-6" />,
  'Flag': <Flag className="w-6 h-6" />,
  'Briefcase': <Briefcase className="w-6 h-6" />,
  'GraduationCap': <GraduationCap className="w-6 h-6" />,
  'Building': <Building className="w-6 h-6" />,
  'Home': <Home className="w-6 h-6" />,
  'Heart': <Heart className="w-6 h-6" />,
  'Star': <Star className="w-6 h-6" />,
  'Flame': <Flame className="w-6 h-6" />,
  'Sun': <Sun className="w-6 h-6" />,
  'Moon': <Moon className="w-6 h-6" />,
  'Coffee': <Coffee className="w-6 h-6" />
};
